/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 24 08:40:11 GMT 2021
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.NameProcessor;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NameProcessor_ESTest extends NameProcessor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NameProcessor nameProcessor0 = new NameProcessor();
      String string0 = nameProcessor0.concatenateFirstNameLastName("D5b[DgB:", "~i2s9'a3!$5afm<");
      assertEquals("D5b[DgB:~i2s9'a3!$5afm<", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NameProcessor nameProcessor0 = new NameProcessor();
      String string0 = nameProcessor0.concatenateFirstNameLastName("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NameProcessor nameProcessor0 = new NameProcessor();
      try { 
        nameProcessor0.concatenateFirstNameLastName("H", (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Last Name cannot be null
         //
         verifyException("tutorial.NameProcessor", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NameProcessor nameProcessor0 = new NameProcessor();
      try { 
        nameProcessor0.concatenateFirstNameLastName((String) null, (String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // First Name cannot be null
         //
         verifyException("tutorial.NameProcessor", e);
      }
  }
}
