/*
 * This file was automatically generated by EvoSuite
 * Sat Jul 24 08:36:49 GMT 2021
 */

package tutorial;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import tutorial.FizzBuzzGame;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FizzBuzzGame_ESTest extends FizzBuzzGame_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FizzBuzzGame fizzBuzzGame0 = new FizzBuzzGame();
      Integer integer0 = new Integer(5);
      String string0 = fizzBuzzGame0.fizzOrBuzz(integer0);
      assertNotNull(string0);
      assertEquals("BUZZ", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FizzBuzzGame fizzBuzzGame0 = new FizzBuzzGame();
      Integer integer0 = new Integer(1727);
      String string0 = fizzBuzzGame0.fizzOrBuzz(integer0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FizzBuzzGame fizzBuzzGame0 = new FizzBuzzGame();
      // Undeclared exception!
      try { 
        fizzBuzzGame0.fizzOrBuzz((Integer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("tutorial.FizzBuzzGame", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FizzBuzzGame fizzBuzzGame0 = new FizzBuzzGame();
      Integer integer0 = new Integer((-93));
      String string0 = fizzBuzzGame0.fizzOrBuzz(integer0);
      assertEquals("FIZZ", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      FizzBuzzGame fizzBuzzGame0 = new FizzBuzzGame();
      Integer integer0 = Integer.valueOf((-1570));
      String string0 = fizzBuzzGame0.fizzOrBuzz(integer0);
      assertNotNull(string0);
      assertEquals("BUZZ", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      FizzBuzzGame fizzBuzzGame0 = new FizzBuzzGame();
      Integer integer0 = new Integer(0);
      String string0 = fizzBuzzGame0.fizzOrBuzz(integer0);
      assertEquals("FIZZ-BUZZ", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FizzBuzzGame fizzBuzzGame0 = new FizzBuzzGame();
      Integer integer0 = new Integer((-142));
      String string0 = fizzBuzzGame0.fizzOrBuzz(integer0);
      assertNull(string0);
  }
}
